name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e-test:
    name: End-to-End Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      USER1_EMAIL: ${{ secrets.USER1_EMAIL }}
      USER1_PASSWORD: ${{ secrets.USER1_PASSWORD }}
      USER2_EMAIL: ${{ secrets.USER2_EMAIL }}
      USER2_PASSWORD: ${{ secrets.USER2_PASSWORD }}
      BANK_NAME: ${{ secrets.BANK_NAME }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
